#!/bin/sh
cd `dirname $0`/../..

branch_name=$(git branch | grep '*' | sed 's/* //')

if [[ $branch_name =~ 'no branch' ]]
then
  exit 0
else
  changed_files=($(git diff --name-only --cached))
  js_files=()

  for filename in "${changed_files[@]}"
  do
    if [[ $filename == *.js ]]; then
      js_files=(${js_files[@]} $filename)
    fi
  done

  if [ ${#js_files[@]} -eq 0 ]; then
    exit 0
  else
    js_files=$(IFS=, ; echo "${js_files[*]}")
    grunt jshint:hook --files="$js_files"
  fi

  if [[ $? != 0 ]]; then
    echo 'Commit aborted'
    exit 1
  fi
fi
