#!/bin/sh
cd `dirname $0`/../..

branch_name=$(git branch | grep '*' | sed 's/* //')

if [[ $branch_name =~ 'no branch' ]]
then
  exit 0
else
  changed_files=($(git diff --name-only --cached))

  for filename in "${changed_files[@]}"
  do
    if [[ $filename == *.js ]]; then
      grunt jshint

      if [[ $? != 0 ]]; then
        echo 'Commit aborted'
        exit 1
      fi

      break
    fi
  done
fi
